"""create process table

Revision ID: 2df822217cbd
Revises: 5e1107633861
Create Date: 2025-10-19 23:09:59.746919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2df822217cbd'
down_revision: Union[str, Sequence[str], None] = '5e1107633861'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('process_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('uri', sa.String(), nullable=True),
    sa.Column('doc_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_process_records_doc_id'), 'process_records', ['doc_id'], unique=False)
    op.create_index(op.f('ix_process_records_id'), 'process_records', ['id'], unique=False)
    op.create_index(op.f('ix_process_records_uri'), 'process_records', ['uri'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_process_records_uri'), table_name='process_records')
    op.drop_index(op.f('ix_process_records_id'), table_name='process_records')
    op.drop_index(op.f('ix_process_records_doc_id'), table_name='process_records')
    op.drop_table('process_records')
    # ### end Alembic commands ###
