"""create extractions records

Revision ID: 5e1107633861
Revises: 80c5ae26b090
Create Date: 2025-10-19 22:36:55.600544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e1107633861'
down_revision: Union[str, Sequence[str], None] = '80c5ae26b090'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extraction_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('uri', sa.String(), nullable=True),
    sa.Column('output_path', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extraction_records_uri'), 'extraction_records', ['uri'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_extraction_records_uri'), table_name='extraction_records')
    op.drop_table('extraction_records')
    # ### end Alembic commands ###
