"""create download_records

Revision ID: 80c5ae26b090
Revises: 
Create Date: 2025-10-19 22:06:30.460148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80c5ae26b090'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('download_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('download_date', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_download_records_file_name'), 'download_records', ['file_name'], unique=False)
    op.create_index(op.f('ix_download_records_id'), 'download_records', ['id'], unique=False)
    op.create_index(op.f('ix_download_records_url'), 'download_records', ['url'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_download_records_url'), table_name='download_records')
    op.drop_index(op.f('ix_download_records_id'), table_name='download_records')
    op.drop_index(op.f('ix_download_records_file_name'), table_name='download_records')
    op.drop_table('download_records')
    # ### end Alembic commands ###
