"""create legifrance table

Revision ID: faa974558d06
Revises: 2df822217cbd
Create Date: 2025-10-19 23:37:07.301610

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "faa974558d06"
down_revision: Union[str, Sequence[str], None] = "2df822217cbd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "legifrance",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("cid", sa.String(), nullable=False),
        sa.Column("nature", sa.String(), nullable=True),
        sa.Column("category", sa.String(), nullable=True),
        sa.Column("ministere", sa.String(), nullable=True),
        sa.Column("etat_juridique", sa.String(), nullable=True),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("full_title", sa.Text(), nullable=True),
        sa.Column("subtitles", sa.Text(), nullable=True),
        sa.Column("number", sa.String(), nullable=True),
        sa.Column("start_date", sa.DateTime(), nullable=True),
        sa.Column("end_date", sa.DateTime(), nullable=True),
        sa.Column("nota", sa.Text(), nullable=True),
        sa.Column("links", sa.JSON(), nullable=True),
        sa.Column("text_content", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("status", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_legifrance_cid"), "legifrance", ["cid"], unique=False)
    op.create_index(op.f("ix_legifrance_id"), "legifrance", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_legifrance_id"), table_name="legifrance")
    op.drop_index(op.f("ix_legifrance_cid"), table_name="legifrance")
    op.drop_table("legifrance")
    # ### end Alembic commands ###
